/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:549adadd-c0d9-4f76-90c4-27c97aee929a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_P2odD9xnP",
    "aws_user_pools_web_client_id": "696s8qmd5ghvv6upsj4ke6783",
    "oauth": {
        "domain": "preyank-preyank.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "myapp://callback/",
        "redirectSignOut": "myapp://signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://2t7bsf5peval7bgo5d5joycupi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "preyank111609-preyank",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_mobile_analytics_app_id": "12c99ea37a774d3e84bdb33ab0d36a0e",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
